name: Run Tests
description: Run the tests
inputs:
  coverage-artifact-name:
    description: 'Name of coverage artifact to be uploaded'
    required: true
    default: 'issue-x'

runs:
  using: "composite"
  steps:
    - name: Run tests
      shell: bash -l {0}
      run: pytest --doctest-modules -v --cov coveralls --cov-report term --cov=vibrav --cov-report xml vibrav
    - name: Upload Coverage
      if: (runner.os == 'Linux') && (matrix.python-version == '3.8') && (always())
      uses: actions/upload-artifact@v2
      with:
        name: code-coverage-report-${{ inputs.coverage-artifact-name }}
        path: coverage.xml
        retention-days: 1
