name: Master

on:
  push:
    branches:
      master

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, 3.10]
    name: Test Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          pip install --upgrade --upgrade-strategy eager -r requirements.txt -e .
      - name: Check out dev exatomic
        uses: actions/checkout@v2
        with:
          repository: exa-analytics/exatomic
          path: './exatomic'
      - name: Install dev exatomic
        run: |
          pip install -e ./exatomic
      - name: Run Tests
        uses: ./.github/workflows/run_tests
        with:
          coverage-artifact-name: ${{ github.workflow }}

  codacy-coverage-reporter:
    runs-on: ubuntu-latest
    needs: run-tests
    name: Codacy Coverage Reporter
    steps:
      - name: Download Coverage Report
        uses: actions/download-artifact@v2
        with:
          name: code-coverage-report-${{ github.workflow }}
      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: coverage.xml

