name: Pull request

on:
  pull_request:

jobs:
  run-tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.7', '3.8', '3.9', '3.10']
      fail-fast: false
    runs-on: ${{ matrix.os }}
    name: Test Python ${{ matrix.python-version }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          pip install --upgrade --upgrade-strategy eager -r requirements.txt -r requirements.dev.txt -e .
      - name: Run Tests
        uses: ./.github/workflows/run_tests
        with:
          coverage-artifact-name: ${{ github.workflow }}

  codacy-coverage-reporter:
    runs-on: ubuntu-latest
    needs: run-tests
    if: ${{ always() }}
    name: Codacy Coverage Reporter
    steps:
      - name: Download Coverage Report
        uses: actions/download-artifact@v2
        with:
          name: code-coverage-report-${{ github.workflow }}
      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: coverage.xml

